import { FieldConfig, DicomConfig } from "../types";

export const STANDARD_CSV_FIELDS: FieldConfig[] = [
  {
    id: 1,
    fieldName: "patientId",
    fieldChineseName: "患者编号",
    name: "患者编号",
    definition: "患者唯一识别号",
    def: "患者唯一识别号",
    attributeType: "直接标识符",
    attr: "直接标识符",
    tech: "假名化(全局)",
    pseudonymType: "SM3",
    description: "采用不可逆加密算法，生成16位哈希值",
    note: "采用不可逆加密算法，生成16位哈希值",
    computeK: "否",
    fieldType: "text",
    category: "admission",
    splitField: ""
  },
  {
    id: 2,
    fieldName: "name",
    fieldChineseName: "患者姓名",
    name: "患者姓名",
    definition: "患者姓名",
    def: "患者姓名",
    attributeType: "直接标识符",
    attr: "直接标识符",
    tech: "属性删除",
    description: "置空",
    note: "置空",
    computeK: "否",
    fieldType: "text",
    category: "admission",
    splitField: "患者姓名"
  },
  {
    id: 3,
    fieldName: "gender",
    fieldChineseName: "性别",
    name: "性别",
    definition: "男、女",
    def: "男、女",
    attributeType: "准标识符",
    attr: "准标识符",
    tech: "原文",
    description: "不涉及敏感隐私，直接保留原文。",
    note: "不涉及敏感隐私，直接保留原文。",
    computeK: "否",
    fieldType: "text",
    category: "admission",
    splitField: "性别"
  },
  {
    id: 4,
    fieldName: "age",
    fieldChineseName: "就诊年龄",
    name: "就诊年龄",
    definition: "患者在就诊当日的周岁年龄",
    def: "患者在就诊当日的周岁年龄",
    attributeType: "准标识符",
    attr: "准标识符",
    tech: "泛化",
    generalizationRules: [
      { from: "青年", to: "18-29" },
      { from: "中年", to: "30-59" },
      { from: "老年", to: "60-100" }
    ],
    description: "1、青年：18-29，中年：30-59，老年：60-100\n2、80岁及以上高位抑制",
    note: "1、青年：18-29，中年：30-59，老年：60-100\n2、80岁及以上高位抑制",
    computeK: "是",
    fieldType: "num",
    category: "admission",
    splitField: "就诊年龄"
  },
  {
    id: 5,
    fieldName: "admissionDate",
    fieldChineseName: "就诊日期",
    name: "就诊日期",
    definition: "患者入院就诊随访的日期",
    def: "患者入院就诊随访的日期",
    attributeType: "准标识符",
    attr: "准标识符",
    tech: "扰动(全局)",
    offsetDays: 14,
    description: "XXXX年XX月XX日，时分秒不保留，向前/后偏移特定天数，保持同一患者的所有日期类字段偏移量一致，不同患者的偏移量不一致",
    note: "XXXX年XX月XX日，时分秒不保留，向前/后偏移特定天数，保持同一患者的所有日期类字段偏移量一致，不同患者的偏移量不一致",
    computeK: "否",
    fieldType: "date",
    category: "admission",
    splitField: ""
  },
  {
    id: 6,
    fieldName: "patientId",
    fieldChineseName: "患者编号",
    name: "患者编号",
    definition: "患者唯一识别号",
    def: "患者唯一识别号",
    attributeType: "直接标识符",
    attr: "直接标识符",
    tech: "假名化(全局)",
    pseudonymType: "SM3",
    description: "采用不可逆加密算法，生成16位哈希值；与“住院信息”中的患者编号保持一致",
    note: "采用不可逆加密算法，生成16位哈希值；与“住院信息”中的患者编号保持一致",
    computeK: "否",
    fieldType: "text",
    category: "check"
  },
  {
    id: 7,
    fieldName: "checkName",
    fieldChineseName: "检查名称",
    name: "检查名称",
    definition: "检查项目名称",
    def: "检查项目名称",
    attributeType: "敏感属性",
    attr: "敏感属性",
    tech: "保留原值",
    description: "例如 上腹部磁共振增强成像",
    note: "例如 上腹部磁共振增强成像",
    computeK: "否",
    fieldType: "text",
    category: "check"
  },
  {
    id: 8,
    fieldName: "checkTime",
    fieldChineseName: "检查时间",
    name: "检查时间",
    definition: "物理检查时间",
    def: "物理检查时间",
    attributeType: "准标识符",
    attr: "准标识符",
    tech: "扰动(全局)",
    description: "XXXX年XX月XX日，时分秒不保留，向前/后偏移特定天数，保持同一患者的所有日期类字段偏移量一致，不同患者的偏移量不一致",
    note: "XXXX年XX月XX日，时分秒不保留，向前/后偏移特定天数，保持同一患者的所有日期类字段偏移量一致，不同患者的偏移量不一致",
    computeK: "否",
    fieldType: "date",
    category: "check"
  },
  {
    id: 9,
    fieldName: "patientId",
    fieldChineseName: "患者编号",
    name: "患者编号",
    definition: "患者唯一识别号",
    def: "患者唯一识别号",
    attributeType: "直接标识符",
    attr: "直接标识符",
    tech: "假名化(全局)",
    pseudonymType: "SM3",
    description: "采用不可逆加密算法，生成16位哈希值；与“住院信息”中的患者编号保持一致",
    note: "采用不可逆加密算法，生成16位哈希值；与“住院信息”中的患者编号保持一致",
    computeK: "否",
    fieldType: "text",
    category: "test"
  },
  {
    id: 10,
    fieldName: "testName",
    fieldChineseName: "检验名称",
    name: "检验名称",
    definition: "检验项目名称",
    def: "检验项目名称",
    attributeType: "敏感属性",
    attr: "敏感属性",
    tech: "保留原值",
    description: "例如 肝功能",
    note: "例如 肝功能",
    computeK: "否",
    fieldType: "text",
    category: "test"
  },
  {
    id: 11,
    fieldName: "testTime",
    fieldChineseName: "检验时间",
    name: "检验时间",
    definition: "标本采集时间",
    def: "标本采集时间",
    attributeType: "准标识符",
    attr: "准标识符",
    tech: "扰动(全局)",
    description: "XXXX年XX月XX日，时分秒不保留，向前/后偏移特定天数，保持同一患者的所有日期类字段偏移量一致，不同患者的偏移量不一致",
    note: "XXXX年XX月XX日，时分秒不保留，向前/后偏移特定天数，保持同一患者的所有日期类字段偏移量一致，不同患者的偏移量不一致",
    computeK: "否",
    fieldType: "date",
    category: "test"
  }
];

export const STANDARD_DICOM_FIELDS: DicomConfig[] = [
  { 
    id: 1, 
    tag: "(0008,0008)", 
    name: "ImageType", 
    fieldChineseName: "图像类型",
    attributeType: "敏感属性",
    attr: "敏感属性",
    tech: "原文", 
    note: "", 
    computeK: "否",
    fieldType: "text"
  },
  { 
    id: 4, 
    tag: "(0010,0020)", 
    name: "Patient ID", 
    fieldChineseName: "Patient ID",
    attributeType: "直接标识符",
    attr: "直接标识符",
    tech: "假名化(全局)", 
    note: "采用不可逆加密算法，生成16位哈希值；与“住院信息”中的患者标识号保持一致", 
    description: "采用不可逆加密算法，生成16位哈希值；与“住院信息”中的患者标识号保持一致", 
    computeK: "否",
    fieldType: "text"
  },
  { 
    id: 2, 
    tag: "(0008,0030)", 
    name: "PatientName", 
    fieldChineseName: "患者姓名",
    attributeType: "直接标识符",
    attr: "直接标识符",
    tech: "假名化", 
    note: "统一更改为“ANONYMIZED”", 
    computeK: "否",
    pseudonymType: "FIXED",
    fixedReplacement: "ANONYMIZED",
    pseudonymizationMode: "直接设置固定值",
    pseudonymizationFixed: "ANONYMIZED",
    fieldType: "text"
  },
  { 
    id: 3, 
    tag: "(0008,0020)", 
    name: "StudyDate", 
    fieldChineseName: "检查日期",
    attributeType: "准标识符",
    attr: "准标识符",
    tech: "扰动(全局)", 
    note: "XXXX年XX月XX日，时分秒不保留，向前/后偏移特定天数，保持同一患者的所有日期类字段偏移量一致，不同患者的偏移量不一致", 
    description: "XXXX年XX月XX日，时分秒不保留，向前/后偏移特定天数，保持同一患者的所有日期类字段偏移量一致，不同患者的偏移量不一致", 
    computeK: "否",
    offsetDirection: "向后",
    offsetDays: 10,
    fieldType: "date"
  }
];
